[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false
idl-build = ["anchor-spl/idl-build"]

[programs.localnet]
hub = "J5FDxQmMpiF4vqKBSWQS3JRGLyE8djRgoHF8QQJJKWM1"
offer = "DGjiY2hKsDpffEgBckNfrAkDt6B5jSxwsHshyQ1cRiP9"
price = "7nkFUfmqKMKrQfm83HxreJHXyJdTK5feYqDEJtNihaw1"
profile = "6HJHAiMENmYh4wW99YtHVY6tGDTzdrNeMtwSpDiyGu1k"
trade = "AxX94noi3AvotjdqnRin3YpKgbQ1rGqQhjkkxpeGUfnM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
