[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
hub = "8xemd2mhu4zi314H6nFTGgXKTVFji4evLSedxKVvk7jH"
profile = "86KWUvm3YK3fsSqSF1iLCRB2mLmHFcGUozFvD823Npf5"
offer = "CZR8LiYhioRCc9qYFBfMkQ3JnkgU2PfAD8fMLN5WrNDo"
trade = "5fRDb9S3Z61fBALmDHNV5EH7GDP8gsCGkQT8eawDL1kE"
escrow = "CfpW1FrK41jj5tv1JRBxgRTqRr7Yeok9HeqnaUMg46VJ"
arbitrator = "J5BNGJ128bxHuWemwaoGkDqy8DVSvsA7o5kpdy9eDoNe"
price_oracle = "CwWd4PCPx85fgREweU3UWWd6kxhtqRVd9xh2iVMT9Rbw"

[programs.devnet]
hub = "8xemd2mhu4zi314H6nFTGgXKTVFji4evLSedxKVvk7jH"
profile = "86KWUvm3YK3fsSqSF1iLCRB2mLmHFcGUozFvD823Npf5"
offer = "CZR8LiYhioRCc9qYFBfMkQ3JnkgU2PfAD8fMLN5WrNDo"
trade = "5fRDb9S3Z61fBALmDHNV5EH7GDP8gsCGkQT8eawDL1kE"
escrow = "CfpW1FrK41jj5tv1JRBxgRTqRr7Yeok9HeqnaUMg46VJ"
arbitrator = "J5BNGJ128bxHuWemwaoGkDqy8DVSvsA7o5kpdy9eDoNe"
price_oracle = "CwWd4PCPx85fgREweU3UWWd6kxhtqRVd9xh2iVMT9Rbw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test"

[test]
startup_wait = 10000
