[toolchain]
anchor_version = "0.31.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
hub = "AHS2kqQDh8Zn3YTqsxJxm9X1uadUuuq7kdddH9BvVkMr"
offer = "7qtvEGEn9bYNMjfjW49aJbYNTT8dC2HmAf6RRdGDvZ27"
profile = "Fsha2mbpkNpHcDw1VCW9XFmJkS9TP1pBjL6wHKzUcKqL"
price = "8JuKMhng6xUdYNVAFbNN2vB6wALwLP8TpMxfLL65ibCi"
trade = "8amGZVCwzB7i26AD39N26N47EMvjaFqRJmQJKYJNEG8Z"

[workspace]
members = [
    "programs/hub",
    "programs/offer",
    "programs/profile",
    "programs/price",
    "programs/trade",
]

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/integration/spl_token_basic.ts"
test-unit = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/hub.ts tests/offer.ts tests/profile.ts tests/price.ts tests/trade.ts"
test-all = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
start-local = "solana-test-validator --reset --quiet --bpf-program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA BPFLoader2111111111111111111111111111111111 --clone metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
local-test = "anchor test --skip-local-validator"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.mainnet-beta.solana.com"
bind_address = "127.0.0.1"
rpc_port = 8899
commitment = "processed"
ledger = ".anchor/test-ledger"
limit_ledger_size = "10000000"

# Required programs for testing
[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" # Token program

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" # Token metadata program
