[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.15"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
localmoney_hub = "9n9sytEuPVqw9dCCdAVb5R47hXFpyyNC3Xo4aFSDdSYx"
localmoney_offer = "6mya23vFa1BwWhmxuPqmM51wPe53VK2Ct3eA6bPyLZqJ"
localmoney_price = "FG8y6dbLj9jxitE9jbairdd79XkiyNoj8u7gRjothJiC"
localmoney_profile = "F9idjQaykbeAD5t8q2D3ozvgPYB54RcNS5zPfpq8E7Sz"
localmoney_trade = "446vbrbtBptN2YoU2GP5MBdx7kt6tUUTomWiKwAuQNM4"

[programs.localnet]
localmoney_hub = "E8JSvDYt3bdqn47X7QbU8HmLuy5oj1CSqsPEWAJjZxgA"
localmoney_offer = "B31zYnvAomR5xNUuHiQc1U9HSKN4Jt2ZBpW5xkosq4hr"
localmoney_price = "Dr5m9zjCj3f7q3u5mvxAW7V9wm9jnrFKX2WLzzeSpKmF"
localmoney_profile = "4posxggSvmFTKCAvNg7K8AU5NQfbmLFSyQLtLdpaPY6a"
localmoney_trade = "GrRvw7wTepPky9pZVVrXKDfvF5RHziKYBegnnRRHoaRo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
