[workspace]
members = ["programs/*"]
resolver = "2"

[workspace.dependencies]
anchor-lang = "0.31.1"
anchor-spl = { version = "0.31.1", features = ["token", "idl-build"] }

[profile.release]
overflow-checks = true
