[workspace]
members = ["shared-types", "programs/*"]
resolver = "2"

[workspace.dependencies]
anchor-lang = "0.31.1"
anchor-spl = { version = "0.31.1", features = ["token", "idl-build"] }
localmoney-shared = { path = "./shared-types", version = "0.1.0" }

[profile.release]
overflow-checks = true
