[package]
name = "localmoney-protocol"
version = "2.0.0"
authors.workspace = true
edition.workspace = true
description = "Common helpers for localmoney-protocol"
license.workspace = true
repository.workspace = true
homepage = "https://localmoney.io"
documentation = "https://localmoney.gitbook.io"

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = []

[dependencies]
cw2.workspace = true
cw20.workspace = true
cosmwasm-std.workspace = true
cw-storage-plus.workspace = true
schemars.workspace = true
serde.workspace = true
thiserror.workspace = true
cw-utils.workspace = true
cw-ownable.workspace = true
cw-migrate-error-derive.workspace = true
semver.workspace = true

[dev-dependencies]
cosmwasm-schema.workspace = true
cosmwasm-vm.workspace = true
anyhow.workspace = true
