pub const BASE_ORACLE_DENOM: &str = "ATOM";
pub const OFFER_DESCRIPTION_LIMIT: usize = 140;
pub const MAX_PLATFORM_FEE: u8 = 10; // 10%
pub const MAX_TRADE_EXPIRATION_TIMER: u64 = 172800; // 2 days
pub const MAX_TRADE_DISPUTE_TIMER: u64 = 86400; // 1 day
pub const MIN_ITEMS_PER_PAGE: u8 = 1; // Pagination
pub const MAX_ITEMS_PER_PAGE: u8 = 30; // Pagination
pub const TRADE_SEED: &[u8] = b"trade"; // For trade PDA derivation
pub const PRICE_CONFIG_SEED: &[u8] = b"price_config"; // For price config PDA
pub const PRICE_ROUTE_SEED: &[u8] = b"price_route"; // For price route PDA
pub const CURRENCY_PRICE_SEED: &[u8] = b"currency_price"; // For currency price PDA
pub const PROFILE_CONFIG_SEED: &[u8] = b"profile_config"; // For profile config PDA
pub const PROFILE_SEED: &[u8] = b"profile"; // For profile PDA 