import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import { Keypair, PublicKey, SystemProgram } from "@solana/web3.js";

import { Hub } from "../target/types/hub";
import { Profile } from "../target/types/profile";
import { Price } from "../target/types/price";
import { Offer } from "../target/types/offer";
import { Trade } from "../target/types/trade";

describe("Basic CPI Test", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const hubProgram = anchor.workspace.Hub as Program<Hub>;
  const profileProgram = anchor.workspace.Profile as Program<Profile>;
  const priceProgram = anchor.workspace.Price as Program<Price>;
  const offerProgram = anchor.workspace.Offer as Program<Offer>;
  const tradeProgram = anchor.workspace.Trade as Program<Trade>;

  it("should build all programs successfully", async () => {
    console.log("Hub Program ID:", hubProgram.programId.toString());
    console.log("Profile Program ID:", profileProgram.programId.toString());
    console.log("Price Program ID:", priceProgram.programId.toString());
    console.log("Offer Program ID:", offerProgram.programId.toString());
    console.log("Trade Program ID:", tradeProgram.programId.toString());
    
    // This test passes if all programs compiled successfully
    console.log("✓ All programs compiled successfully");
  });

  it("should have CPI modules available", async () => {
    // Test that CPI modules are generated by Anchor for the Hub program
    const hubCpi = hubProgram.cpi;
    console.log("Hub CPI module exists:", !!hubCpi);
    
    // Log available CPI methods if they exist
    if (hubCpi) {
      console.log("Hub CPI methods available");
    }
    
    console.log("✓ CPI modules verified");
  });
});